{
 "title": "Home",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Comsumption",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "logs",
     "select": [
      [
       { "params": [ "output_w" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Power usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "logs",
     "query": "SELECT sum(ph1) / 10 as online FROM (SELECT non_negative_difference(\"discharge\") AS ph1 FROM \"autogen\".\"logs\" WHERE (\"state\"::tag = 'GridCharging')) WHERE $timeFilter GROUP BY time(1h) \n\n",
     "select": [
      [
       { "params": [ "discharge" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "logs",
     "query": "SELECT sum(ph1) / 10 as offline FROM (SELECT non_negative_difference(\"discharge\") AS ph1 FROM \"autogen\".\"logs\" WHERE (\"state\"::tag != 'GridCharging')) WHERE $timeFilter GROUP BY time(1h) ",
     "select": [
      [
       { "params": [ "discharge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Battery usage (kWh)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 7 },
   "targets": [
    {
     "query": "SELECT CUMULATIVE_SUM(SUM(ph1)) / 10 as battery_power_spent FROM (SELECT non_negative_difference(\"discharge\") AS ph1 FROM \"autogen\".\"logs\" WHERE (\"state\"::tag != 'GridCharging')) WHERE $timeFilter GROUP BY time(10m) "
    }
   ]
  },
  {
   "title": "Battery power (amps)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 7 },
   "targets": [
    {
     "query": "SELECT \"bat_amps\" FROM \"autogen\".\"logs\" WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "kWh consumed",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "SELECT non_negative_difference(\"discharge\") / 10 AS ph1 FROM \"autogen\".\"logs\" WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "Battery Volts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 15 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "logs",
     "select": [
      [
       { "params": [ "bat_volts" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Input AC",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 15 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "logs",
     "select": [
      [
       { "params": [ "ac" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Current ",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "logs",
     "query": "SELECT\n  LAST(bat_amps) / 1000 as \"bat_amps\", \n  LAST(output_w) as \"output_w\", LAST(bat_volts) as \"bat_volts\", LAST(output_va) as \"output_va\"\nFROM \"autogen\".\"logs\"\n",
     "select": [
      [
       { "params": [ "bat_volts" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}